### ISSUE TITLE
Missing issue templates

### ISSUE THREAD

**Issue by FahimFBA** [Pradumnasaraf/Wish-Eddie#67]
I do understand that this is a small repo; therefore, you might not want any issue template for now. But, as I am going to suggest an enhancement in the issue, I was searching for a relevant issue template. So, I thought about mentioning that here as well. 

Thank you.

**Comment by Pradumnasaraf** [comment]
Thank you, Fahim for raising the issue. After today no one will be able to make the PRs. Thanks why I keep it simple.
Thanks again.
