### ISSUE TITLE
Implementation of an alphabetical order

### ISSUE THREAD

**Issue by FahimFBA** [Pradumnasaraf/Wish-Eddie#68]
I think if we implement the alphabetical order based on the people's names, then the repo would look more beautiful. I was trying to search people here, and I was expecting an alphabetical order like other projects.

**Comment by Pradumnasaraf** [comment]
Hey, the Whole point was to create 1st come 1st server mini competition, haha. That's why I did it that way. Thank you for raising the issue. After all PR I will sort it in alphabetical order. Thank you so much for rasing the issue.
